export const PRODUCER = {
  gny: 'gny',
  knh: 'knh',
  kmh: 'kmh',
  kej: 'kej',
  khj: 'khj',
  nsb: 'nsb',
  bsj: 'bsj',
  sde: 'sde',
  syb: 'syb',
  shj: 'shj',
  yjy: 'yjy',
  ojh: 'ojh',
  yjh: 'yjh',
  lar: 'lar',
  lyj: 'lyj',
  lyr: 'lyr',
  lwj: 'lwj',
  lja: 'lja',
  jsh: 'jsh',
  jys: 'jys',
  jde: 'jde',
  jyn: 'jyn',
  jej: 'jej',
  jsb: 'jsb',
  hyr: 'hyr',
  hyd: 'hyd',
} as const;

export type Producer = keyof typeof PRODUCER;

export const PRODUCER_NAME = {
  gny: '곽나영',
  knh: '김나현',
  kmh: '김미현',
  kej: '김의정',
  khj: '김현주',
  nsb: '남시본',
  bsj: '배상진',
  sde: '서다은',
  syb: '송예빈',
  shj: '송희주',
  yjy: '양준녕',
  ojh: '오지현',
  yjh: '윤지현',
  lar: '이아림',
  lyj: '이연주',
  lyr: '이예림',
  lwj: '이원준',
  lja: '이지안',
  jsh: '장수현',
  jys: '전유석',
  jde: '정다은',
  jyn: '정유나',
  jej: '조은지',
  jsb: '진수별',
  hyr: '한예리',
  hyd: '홍이도',
} as const;

export type ProducerName = typeof PRODUCER_NAME;

export const PRODUCER_TITLE = {
  gny: '곽테일',
  knh: 'KESSLER',
  kmh: 'FLOVE',
  kej: '여우 영이의 첫외출',
  khj: 'òsso',
  nsb: '공감각 악보',
  bsj: '_amily',
  sde: 'MAKESURE',
  syb: 'DOT',
  shj: 'miol',
  yjy: 'Divenamic',
  ojh: '오메가메',
  yjh: 'Comma',
  lar: 'Ahoy',
  lyj: 'US BEE',
  lyr: '차차',
  lwj: '쓰담쓰담',
  lja: 'aqua 26°C',
  jsh: 'MONTRER',
  jys: 'dolittle',
  jde: 'Jalza',
  jyn: '어디둥지',
  jej: '6060',
  jsb: '休_휴',
  hyr: 'Colorado bitches',
  hyd: '그루터기',
} as const;

export type ProducerTitle = typeof PRODUCER_TITLE;

export const PRODUCER_SUBTITLE = {
  gny: 'kwacktail',
  ojh: 'omegame',
  lyr: 'cha cha',
  lwj: 'sdam sdam',
} as const;
